Implementations of Jacoco, Cobertura and Mutation testing parser
uhafner/coverage-model pull request #24
Opened 2022-08-19 16:48 UTC by mbauerness

2022-08-19 16:51 UTC, mbauerness commented on src/main/java/edu/hm/hafner/model/Node.java
>                  mergeLeaves(this.getMetricsDistribution(), other.getMetricsDistribution());
6 Tests schlagen an dieser Stelle noch fehl, weil versucht wird, aus Node-Metriken (FILE und METHOD) Blätter zu erstellen. Können Sie mir die Theorie dahinter erklären, damit ich das fixen kann?

2022-08-19 16:53 UTC, mbauerness commented on src/main/java/edu/hm/hafner/coverage/CoverageLeaf.java
>      }
Und hier schlägt der Test auch mit 
`EqualsVerifier found a problem in class edu.hm.hafner.coverage.CoverageLeaf.
-> Symmetry:
  [one]: 50.00% (1/2)
does not equal superclass instance`
fehl. Dann muss ja ein Fehler in der equals-Methode vorliegen, die ich von IntelliJ generieren lassen habe. Vielleicht sehen Sie da ja mehr als ich...

2022-08-22 22:32 UTC, uhafner commented on src/main/java/edu/hm/hafner/model/Node.java
>                  mergeLeaves(this.getMetricsDistribution(), other.getMetricsDistribution());
Das ist wohl noch ein Bug beim Merge. Die MetricsDistribution enthält alle Metriken, es sollten aber nur die Leaves gemerged werden. Entweder muss man die die MetricsDistribution filtern oder eine andere Methode nehmen, die nur die Leaf Metriken liefert.

2022-08-22 22:39 UTC, uhafner commented on src/main/java/edu/hm/hafner/coverage/CoverageLeaf.java
>      }
Ich glaube, es langt die Oberklasse auf Abstract zu setzen. Sonst prüft der, ob eine Superklassen Instanz equals zu einer CoverageNode ist. 

https://jqno.nl/equalsverifier/errormessages/symmetry-does-not-equal-superclass-instance/

2022-09-16 17:18 UTC, uhafner requested changes
Vom Ergebnis sieht das schon mal prima aus: ich denke, von der Struktur lässt sich manches noch mehr objekt-orientiert gestalten, siehe einzelne Anmerkungen...

2022-09-16 17:18 UTC, uhafner commented on src/main/java/edu/hm/hafner/model/Node.java
> +    /**
Könnte besser in die `ModuleNode` verschoben werden

2022-09-16 17:18 UTC, uhafner commented on src/main/java/edu/hm/hafner/parser/PitestParser.java
> +    private String currentFileName = null;
`@CheckForNull`

2022-09-16 17:18 UTC, uhafner commented on src/main/java/edu/hm/hafner/parser/PitestParser.java
> +        PackageNode currentPackageNode = null;
`find`, siehe Cobertura

2022-09-16 17:18 UTC, uhafner commented on src/main/java/edu/hm/hafner/parser/PitestParser.java
> +        classNode = currentClassNode;
Wenn  `find` nicht passt, sollte der Code in der `Node` implementiert werden

2022-10-07 14:12 UTC, mbauerness commented on src/main/java/edu/hm/hafner/metric/Node.java
> +// TODO: Make sure that we do not have children with the same name in the same node
Was passiert dann mit einem Report, bei dem zB. die Packagenamen fehlen (wie der Beispielreport in Cobertura)?
Davon abgesehen: Jacoco und Cobertura haben von selbst pro File, Klasse, Methode etc ein eigenes Element. Bei Pit kann und muss man selbst dafür sorgen, dass zB die überladenen Methoden jeweils eigene Nodes sind

2022-10-07 14:14 UTC, mbauerness commented on src/main/java/edu/hm/hafner/metric/Value.java
> +                .isFalse("Cannot create a value with a node metric");*/
Das Problem beim Überprüfen auf Node und Leaf-Metric: in der Methode getMetricsDistribution werden Values (Coverage) erstellt, die die coverage in Modulen, Dateien, Klassen, ... angeben. Man müsste die Methode erst neu schreiben, damit man das Erstellen von Values mit mit Node-Metriken nicht mehr erlaubt

2022-10-07 21:18 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/Value.java
> +                .isFalse("Cannot create a value with a node metric");*/
Dass stimmt. Ist es nicht sinnvoller, den Ensure Teil einfach zu entfernen? Ich denke eine Value mit dem Typ File und dem Ergebnis 4/5 Überdeckung ist ja schon sinnvoll.

2022-10-07 21:23 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/Node.java
> +// TODO: Make sure that we do not have children with the same name in the same node
Wir können das erst mal so lassen wie das ist. Für die Suche hinterher in der GUI wäre es halt sinnvoll, jedes Element eindeutig zu identifizieren.

2022-10-08 07:01 UTC, mbauerness commented on src/main/java/edu/hm/hafner/metric/Value.java
> +                .isFalse("Cannot create a value with a node metric");*/
Ich habs noch drin gelassen, weil das als TODO drinnen stand und einen Teil von dem TODO (keine Nodes mit Leaf Metriken) habe ich umgesetzt. Dann entferne ich den Kommentar

2022-10-08 07:02 UTC, mbauerness commented on src/main/java/edu/hm/hafner/metric/Node.java
> +// TODO: Make sure that we do not have children with the same name in the same node
Das sollte in Jacoco und Cobertura sowieso gegeben sein. Für die Methoden habe ich noch die Signatur mit drin, damit die auch jeweils eine eigene Node bekommen

2022-10-08 15:09 UTC, uhafner approved these changes

2022-10-08 15:09 UTC, merged