Support for "Changed Files Coverage"
uhafner/coverage-model pull request #62
Opened 2023-01-21 15:07 UTC by fo-code

I added support for "Changed Files Coverage". I thought that would be a good name for the metric since it describes all covered lines of files that have been changed.

2023-01-24 12:21 UTC, uhafner requested changes

2023-01-24 12:21 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/FileNode.java
> +            return Optional.of(copy);
Can't we simply copy the file with all children and values?

2023-01-24 12:21 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/FileNode.java
> +                return new CoverageBuilder().setMetric(Metric.BRANCH)
Good spot!

2023-01-24 12:21 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/Node.java
> +     * Creates a new coverage tree that represents the Changed Files Coverage. This new tree will contain only those
Maybe we should use modified lines and modified files everywhere?

2023-01-24 12:21 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/Node.java
> +    }
It makes sense to extract that method into a private method that gets the mapping `Function` as an argument (I should have done this already in my code 🙈 )

2023-02-04 09:43 UTC, fo-code commented on src/main/java/edu/hm/hafner/metric/FileNode.java
> +            return Optional.of(copy);
You are right!

2023-02-04 09:44 UTC, fo-code commented on src/main/java/edu/hm/hafner/metric/Node.java
> +     * Creates a new coverage tree that represents the Changed Files Coverage. This new tree will contain only those
Yes, that sounds goot to me.

2023-02-04 09:59 UTC, fo-code commented on src/main/java/edu/hm/hafner/metric/Node.java
> +    }
Yes, true!

2023-02-05 13:04 UTC, uhafner approved these changes

2023-02-05 13:05 UTC, uhafner commented on src/main/java/edu/hm/hafner/metric/Metric.java
> +        ));
Where do you need this method?

2023-02-05 13:06 UTC, merged